### ISSUE TITLE
accept empty strings

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/libmei#2]
The `AttConverter` should accept empty strings without complaining and just return `none` values. 
This would make code handling easier as you don't have to check every time if a passed string is empty just to prevent a warning message.

**Comment by lpugin** [comment]
Could you provide an example? Is this for the MusicXML import?

**Comment by rettinghaus** [comment]
It is mainly for Verovio's MusicXML import. 
Take a look at this snippet: 
```cpp
std::string placeStr = GetAttributeValue(xmlMordent.node(), "placement");
if (!placeStr.empty()) mordent->SetPlace(mordent->AttPlacement::StrToStaffrel(placeStr.c_str()));
```
I could pass the attribute value directly to the AttConverter, but if it's empty, I get a warning. So every time the AttCoverter is used I have to use a string and check if that is empty.

**Comment by lpugin** [comment]
OK, I see. Can't you set the `logWarning` parameter to `false`?

**Comment by rettinghaus** [comment]
Could do that, but sometimes it is needed to filter nonsense values. I thought more of something like 
``if (logWarning && !value.empty())`` for all ``AttConverter::StrToSomeThing`` functions.

**Comment by lpugin** [comment]
Yes, this makes sense.

**Comment by lpugin** [comment]
Changed 64df98255af7feac7b5ce5d3362637e52f272854
