### ISSUE TITLE
Reading/writing numerical values

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/libmei#9]
All cases where we have integer or decimal attribute values are treated as empty with value "0". That makes it impossible to explicitly set encoded values to zero in Verovio (e.g. `beam@slope`).

**Comment by lpugin** [comment]
No, we override the default in many places
https://github.com/rism-digital/libmei/blob/develop/tools/includes/vrv/config.yml

**Comment by rettinghaus** [comment]
We override _positive_ integer values by setting the default to -1. But this will not work with e.g. `@trans.diat`.

**Comment by lpugin** [comment]
Could you explain why it would not work if you change it in `config.yml`? Sorry, I don't understand

**Comment by rettinghaus** [comment]
Oh, I overlooked the `VRV_UNSET` possiblity. Sorry.
